PROFILE_ID="lavender-4.4"
PROFILE_DEVICE="lavender"
PROFILE_KERNEL_FAMILY="4.4"
PROFILE_ARCH="arm64"
PROFILE_KERNEL_REPO="https://github.com/projects-nexus/nexus_kernel_xiaomi_lavender.git"
PROFILE_KERNEL_REF="13"
PROFILE_KERNEL_REF_TYPE="branch"
PROFILE_DEFCONFIG="lavender_defconfig"
PROFILE_CONFIG_FRAGMENT="none"
PROFILE_SCHEDULER_PROFILE="hmp-eas"
PROFILE_PATCH_PROFILE="none"
PROFILE_UPSTREAM_PROFILE="none"
PROFILE_LTO_PLUS="false"
PROFILE_ROM_FAMILY="legacy"
PROFILE_ANYKERNEL_PROFILE="lavender-4.4"
PROFILE_ANYKERNEL3_REF="master"
PROFILE_PACKAGE_ANYKERNEL="true"
PROFILE_DYNAMIC_PARTITION="true"
PROFILE_GKI="false"
PROFILE_SOURCE_LABEL="Nexus CAF lavender"
PROFILE_KSU_NEXT_4_4_REF="v1.1.1"
PROFILE_KSU_NEXT_LEGACY_REF="v3.4.0"
PROFILE_KSU_NEXT_GKI_REF="v3.4.0"
PROFILE_RESUKISU_REF="v4.2.0-rc3"
PROFILE_SUKISU_ULTRA_REF="7fbbb1f12e2410b69c8ebf958be84f165b8d0c93"

PROFILE_NONGKI_4_4_HOOKS="true"
PROFILE_NONGKI_4_4_MODE="auto"
