PROFILE_ID="garnet-oss"
DEVICE_NAMES="garnet 2312DRA50G"
ROM_FAMILY="oss"
KERNEL_FAMILY="5.10"
BLOCK="boot"
IS_SLOT_DEVICE="auto"
RAMDISK_COMPRESSION="auto"
PATCH_VBMETA_FLAG="auto"
DO_DEVICECHECK="1"
DO_MODULES="0"
DO_SYSTEMLESS="0"
FLASH_DTBO="1"
NO_MAGISK_CHECK="0"
ANYKERNEL3_REF="master"
KERNEL_STRING="CI-Build Kernel | Garnet | OSS | Linux 5.10"
