PROFILE_ID="lavender-4.19"
DEVICE_NAMES="lavender aosp_lavender lineage_lavender"
ROM_FAMILY="custom-android"
KERNEL_FAMILY="4.19"
BLOCK="boot"
IS_SLOT_DEVICE="0"
RAMDISK_COMPRESSION="auto"
PATCH_VBMETA_FLAG="auto"
DO_DEVICECHECK="1"
DO_MODULES="0"
DO_SYSTEMLESS="0"
FLASH_DTBO="0"
NO_MAGISK_CHECK="0"
ANYKERNEL3_REF="master"
KERNEL_STRING="Zairenkai Kernel | Lavender | Linux 4.19"
