#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# Reuse the canonical variant normalization/label helpers so every CI
# component renders root-manager names consistently.
# shellcheck source=/dev/null
source "$SCRIPT_DIR/lib/common.sh"

MODE="${1:-single}"
BUILD_INFO="${BUILD_INFO:-}"
SOURCE_DIR="${SOURCE_DIR:-}"
OUT_FILE="${OUT_FILE:-}"
VARIANT="${VARIANT:-unknown}"
INFO_ROOT="${INFO_ROOT:-}"

get_info() {
  local key="$1" file="$2"
  awk -F= -v k="$key" '$1==k {sub(/^[^=]*=/, ""); print; exit}' "$file" 2>/dev/null || true
}
# get_info_any <file> <key>...: first non-empty value among several keys.
get_info_any() {
  local file="$1" key value
  shift
  for key in "$@"; do
    value="$(get_info "$key" "$file")"
    [[ -n "$value" ]] && { printf '%s\n' "$value"; return 0; }
  done
  return 0
}
md_code() {
  printf '`%s`' "${1:-n/a}"
}

single() {
  [[ -n "$BUILD_INFO" && -f "$BUILD_INFO" ]] || { echo "ERROR: BUILD_INFO missing" >&2; exit 2; }
  [[ -n "$OUT_FILE" ]] || { echo "ERROR: OUT_FILE missing" >&2; exit 2; }
  mkdir -p "$(dirname "$OUT_FILE")"
  {
    VARIANT_CANONICAL="$(normalize_variant "$VARIANT" 2>/dev/null || printf '%s' "$VARIANT")"
    printf '# Zairenkai Kernel Changelog — %s\n\n' "$(variant_label "$VARIANT_CANONICAL")"
    echo '## Target'
    printf -- '- Profile: '; md_code "$(get_info build_profile "$BUILD_INFO")"; echo
    printf -- '- Device: '; md_code "$(get_info device "$BUILD_INFO")"; echo
    printf -- '- Kernel: '; md_code "$(get_info kernel_version "$BUILD_INFO")"; echo
    printf -- '- Family: '; md_code "$(get_info kernel_family "$BUILD_INFO")"; echo
    printf -- '- Defconfig: '; md_code "$(get_info defconfig "$BUILD_INFO")"; echo
    printf -- '- Scheduler: '; md_code "$(get_info_any "$BUILD_INFO" scheduler scheduler_detected)"; echo
    printf -- '- Dynamic partition: '; md_code "$(get_info dynamic_partition "$BUILD_INFO")"; echo
    printf -- '- GKI: '; md_code "$(get_info gki "$BUILD_INFO")"; echo
    printf -- '- AnyKernel profile: '; md_code "$(get_info anykernel_profile "$BUILD_INFO")"; echo
    echo
    echo '## Source'
    printf -- '- Repository: '; md_code "$(get_info kernel_repo "$BUILD_INFO")"; echo
    printf -- '- Ref: '; md_code "$(get_info ref "$BUILD_INFO")"; echo
    printf -- '- Commit: '; md_code "$(get_info commit_sha "$BUILD_INFO")"; echo
    printf -- '- HEAD: %s\n' "$(get_info_any "$BUILD_INFO" commit_subject commit)"
    echo
    echo '## Kernel commits'
    if [[ -n "$SOURCE_DIR" && -d "$SOURCE_DIR/.git" ]]; then
      git -C "$SOURCE_DIR" log -12 --date=short --pretty='- `%h` %s (%ad)' 2>/dev/null || true
    else
      echo '- Source history was not retained in the artifact stage.'
    fi
    echo
    echo '## Build'
    printf -- '- Toolchain: %s %s\n' "$(md_code "$(get_info toolchain "$BUILD_INFO")")" "$(md_code "$(get_info toolchain_version "$BUILD_INFO")")"
    printf -- '- LLVM IAS: '; md_code "$(get_info llvm_ias "$BUILD_INFO")"; echo
    printf -- '- Root manager: '; md_code "$(get_info ksu_provider "$BUILD_INFO")"; echo
    printf -- '- Root version: '; md_code "$(get_info ksu_version "$BUILD_INFO")"; echo
    printf -- '- Root commit: '; md_code "$(get_info ksu_commit "$BUILD_INFO")"; echo
    printf -- '- Kernel image: '; md_code "$(get_info_any "$BUILD_INFO" kernel_image anykernel_zip)"; echo
    echo
    echo 'Generated by ci-build.'
  } > "$OUT_FILE"
}

aggregate() {
  : "${INFO_ROOT:?INFO_ROOT is required}"
  : "${OUT_FILE:?OUT_FILE is required}"
  mapfile -t files < <(find "$INFO_ROOT" -type f -name changelog.md ! -path "$(realpath -m "$OUT_FILE" 2>/dev/null || printf '%s' "$OUT_FILE")" | sort)

  # Be resilient to callers that collected build-info files but not the
  # per-variant changelog. Generate the missing changelog beside each
  # build-info, then aggregate the complete set.
  if ((${#files[@]} == 0)); then
    while IFS= read -r info_file; do
      dir="$(dirname "$info_file")"
      variant="$(get_info root_variant "$info_file")"
      [[ -n "$variant" ]] || variant="$(get_info variant "$info_file")"
      [[ -n "$variant" ]] || variant=unknown
      generated="$dir/changelog.md"
      if [[ ! -f "$generated" ]]; then
        BUILD_INFO="$info_file" VARIANT="$variant" OUT_FILE="$generated" bash "$0" single >/dev/null
      fi
    done < <(find "$INFO_ROOT" -type f -name build-info.txt | sort)
    mapfile -t files < <(find "$INFO_ROOT" -type f -name changelog.md ! -path "$(realpath -m "$OUT_FILE" 2>/dev/null || printf '%s' "$OUT_FILE")" | sort)
  fi

  ((${#files[@]} > 0)) || { echo "ERROR: no per-variant changelog/build-info files found under $INFO_ROOT" >&2; exit 2; }
  mkdir -p "$(dirname "$OUT_FILE")"
  {
    echo '# Zairenkai Kernel Release Changelog'
    echo
    providers=()
    for file in "${files[@]}"; do
      info_file="$(dirname -- "$file")/build-info.txt"
      v="$(get_info root_variant "$info_file")"
      [[ -n "$v" ]] || v="$(get_info variant "$info_file")"
      [[ -n "$v" ]] || v="$(get_info ksu_provider "$info_file")"
      if [[ -n "$v" ]]; then
        v="$(normalize_variant "$v" 2>/dev/null || printf '%s' "$v")"
        providers+=("$(variant_label "$v")")
      fi
    done
    joined="$(printf '%s, ' "${providers[@]}")"
    printf 'This release contains the %s builds for the selected target profile.\n' "${joined%, }"
    echo
    for file in "${files[@]}"; do
      cat "$file"
      echo
      echo '---'
      echo
    done
  } > "$OUT_FILE"
}

case "$MODE" in
  single) single ;;
  aggregate) aggregate ;;
  *) echo "usage: $0 single|aggregate" >&2; exit 2 ;;
esac
