#!/usr/bin/env bash
# Idempotent GitHub release publisher used by GitHub Actions and Harness.
set -Eeuo pipefail

: "${GH_TOKEN:?GH_TOKEN is required}"
: "${GH_REPOSITORY:?GH_REPOSITORY is required}"
: "${RELEASE_TAG:?RELEASE_TAG is required}"
: "${ASSET_DIR:?ASSET_DIR is required}"

API="https://api.github.com"
RELEASE_NAME="${RELEASE_NAME:-Zairenkai Kernel ${RELEASE_TAG}}"
RELEASE_DRAFT="${RELEASE_DRAFT:-false}"
RELEASE_PRERELEASE="${RELEASE_PRERELEASE:-false}"
RELEASE_BODY_FILE="${RELEASE_BODY_FILE:-}"
RELEASE_BODY="${RELEASE_BODY:-Artifacts generated by Zairenkai CI.}"
RELEASE_CLEAN_STAGING="${RELEASE_CLEAN_STAGING:-false}"
AUTH=(
  -H "Authorization: Bearer ${GH_TOKEN}"
  -H "Accept: application/vnd.github+json"
  -H "X-GitHub-Api-Version: 2022-11-28"
)

urlencode() {
  python3 - "$1" <<'PY'
import sys, urllib.parse
print(urllib.parse.quote(sys.argv[1], safe=""))
PY
}

json_payload() {
  python3 - "$1" "$2" "$3" "$4" "$5" <<'PY'
import json, sys, os
body = open(sys.argv[5], encoding='utf-8').read() if sys.argv[5] else os.environ.get('RELEASE_BODY', '')
print(json.dumps({
    "tag_name": sys.argv[1],
    "name": sys.argv[2],
    "body": body,
    "draft": sys.argv[3].lower() == 'true',
    "prerelease": sys.argv[4].lower() == 'true',
}))
PY
}

mkdir -p "$ASSET_DIR"
shopt -s nullglob
ASSETS=("$ASSET_DIR"/*)
((${#ASSETS[@]} > 0)) || { echo "ERROR: no assets to publish in $ASSET_DIR" >&2; exit 1; }

if [[ -n "$RELEASE_BODY_FILE" ]]; then
  [[ -f "$RELEASE_BODY_FILE" ]] || { echo "ERROR: RELEASE_BODY_FILE not found: $RELEASE_BODY_FILE" >&2; exit 1; }
fi

TAG_ENC="$(urlencode "$RELEASE_TAG")"
RELEASE_JSON="$(mktemp)"
trap 'rm -f "$RELEASE_JSON"' EXIT

# Create or update the release. Updating makes reruns deterministic instead of
# producing duplicate releases/assets for the same tag.
if curl -fsSL "${AUTH[@]}" "$API/repos/${GH_REPOSITORY}/releases/tags/${TAG_ENC}" > "$RELEASE_JSON" 2>/dev/null; then
  RELEASE_ID="$(python3 - "$RELEASE_JSON" <<'PY'
import json,sys
print(json.load(open(sys.argv[1],encoding='utf-8'))['id'])
PY
)"
  curl -fsSL -X PATCH "${AUTH[@]}" -H 'Content-Type: application/json' \
    "$API/repos/${GH_REPOSITORY}/releases/${RELEASE_ID}" \
    --data "$(json_payload "$RELEASE_TAG" "$RELEASE_NAME" "$RELEASE_DRAFT" "$RELEASE_PRERELEASE" "${RELEASE_BODY_FILE:-}")" > "$RELEASE_JSON"
else
  curl -fsSL -X POST "${AUTH[@]}" -H 'Content-Type: application/json' \
    "$API/repos/${GH_REPOSITORY}/releases" \
    --data "$(json_payload "$RELEASE_TAG" "$RELEASE_NAME" "$RELEASE_DRAFT" "$RELEASE_PRERELEASE" "${RELEASE_BODY_FILE:-}")" > "$RELEASE_JSON"
  RELEASE_ID="$(python3 - "$RELEASE_JSON" <<'PY'
import json,sys
print(json.load(open(sys.argv[1],encoding='utf-8'))['id'])
PY
)"
fi

UPLOAD_URL="$(python3 - "$RELEASE_JSON" <<'PY'
import json,sys
print(json.load(open(sys.argv[1],encoding='utf-8')).get('upload_url','').split('{',1)[0])
PY
)"
[[ -n "$UPLOAD_URL" ]] || { echo "ERROR: release upload URL missing" >&2; exit 1; }

# Remove same-named assets before uploading refreshed artifacts.
ASSETS_JSON="$(curl -fsSL "${AUTH[@]}" "$API/repos/${GH_REPOSITORY}/releases/${RELEASE_ID}/assets?per_page=100")"
while IFS=$'\t' read -r asset_id asset_name; do
  [[ -n "$asset_id" ]] || continue
  for file in "${ASSETS[@]}"; do
    [[ "$(basename "$file")" == "$asset_name" ]] || continue
    echo "[release] replacing existing asset $asset_name"
    curl -fsSL -X DELETE "${AUTH[@]}" "$API/repos/${GH_REPOSITORY}/releases/assets/${asset_id}" >/dev/null
  done
done < <(python3 - "$ASSETS_JSON" <<'PY'
import json,sys
for a in json.loads(sys.argv[1]):
    print(f"{a['id']}\t{a['name']}")
PY
)

# Final publication removes per-variant draft assets staged during the build,
# leaving only the canonical release assets.
if [[ "${RELEASE_CLEAN_STAGING,,}" == "true" ]]; then
  while IFS=$'\t' read -r asset_id asset_name; do
    [[ -n "$asset_id" ]] || continue
    [[ "$asset_name" == staging-* ]] || continue
    echo "[release] removing staged asset $asset_name"
    curl -fsSL -X DELETE "${AUTH[@]}" "$API/repos/${GH_REPOSITORY}/releases/assets/${asset_id}" >/dev/null
  done < <(python3 - "$ASSETS_JSON" <<'PY'
import json,sys
for a in json.loads(sys.argv[1]):
    print(f"{a['id']}\t{a['name']}")
PY
)
fi

for file in "${ASSETS[@]}"; do
  [[ -f "$file" ]] || continue
  name="$(basename "$file")"
  encoded="$(urlencode "$name")"
  echo "[release] uploading $name"
  curl -fsSL -X POST "${AUTH[@]}" \
    -H 'Content-Type: application/octet-stream' \
    --data-binary "@$file" \
    "${UPLOAD_URL}?name=${encoded}" >/dev/null
done

echo "[release] published tag=$RELEASE_TAG assets=${#ASSETS[@]}"
