#!/usr/bin/env bash
# Idempotent GitHub release publisher used by GitHub Actions and Harness.
set -Eeuo pipefail

: "${GH_TOKEN:?GH_TOKEN is required}"
: "${GH_REPOSITORY:?GH_REPOSITORY is required}"
: "${RELEASE_TAG:?RELEASE_TAG is required}"
: "${ASSET_DIR:?ASSET_DIR is required}"

API="${GITHUB_API:-https://api.github.com}"
RELEASE_NAME="${RELEASE_NAME:-Zairenkai Kernel ${RELEASE_TAG}}"
RELEASE_DRAFT="${RELEASE_DRAFT:-false}"
RELEASE_PRERELEASE="${RELEASE_PRERELEASE:-false}"
RELEASE_BODY_FILE="${RELEASE_BODY_FILE:-}"
RELEASE_BODY="${RELEASE_BODY:-Artifacts generated by Zairenkai CI.}"
RELEASE_CLEAN_STAGING="${RELEASE_CLEAN_STAGING:-false}"
# New tags are created on the commit that was actually built, not on the
# default branch head (GitHub's default when target_commitish is omitted).
TARGET_COMMITISH="${TARGET_COMMITISH:-${CI_BUILD_SHA:-${GITHUB_SHA:-}}}"
AUTH=(
  -H "Authorization: Bearer ${GH_TOKEN}"
  -H "Accept: application/vnd.github+json"
  -H "X-GitHub-Api-Version: 2022-11-28"
)

urlencode() {
  python3 - "$1" <<'PY'
import sys, urllib.parse
print(urllib.parse.quote(sys.argv[1], safe=""))
PY
}

# json_payload <out-file>: write the release JSON to a file. The body can be a
# large changelog, so it is sent with --data-binary @file instead of argv.
json_payload() {
  python3 - "$1" "$RELEASE_TAG" "$RELEASE_NAME" "$RELEASE_DRAFT" "$RELEASE_PRERELEASE" \
    "${RELEASE_BODY_FILE:-}" "$TARGET_COMMITISH" <<'PY'
import json, os, sys
out, tag, name, draft, pre, body_file, target = sys.argv[1:8]
body = open(body_file, encoding='utf-8').read() if body_file else os.environ.get('RELEASE_BODY', '')
payload = {
    "tag_name": tag,
    "name": name,
    "body": body[:125000],  # GitHub rejects release bodies above 125000 chars.
    "draft": draft.lower() == 'true',
    "prerelease": pre.lower() == 'true',
}
if target:
    payload["target_commitish"] = target
with open(out, "w", encoding="utf-8") as fh:
    json.dump(payload, fh)
PY
}

mkdir -p "$ASSET_DIR"
mapfile -t ASSETS < <(find "$ASSET_DIR" -maxdepth 1 -type f -print | sort)
((${#ASSETS[@]} > 0)) || { echo "ERROR: no files to publish in $ASSET_DIR" >&2; exit 1; }

if [[ -n "$RELEASE_BODY_FILE" ]]; then
  [[ -f "$RELEASE_BODY_FILE" ]] || { echo "ERROR: RELEASE_BODY_FILE not found: $RELEASE_BODY_FILE" >&2; exit 1; }
fi

TAG_ENC="$(urlencode "$RELEASE_TAG")"
RELEASE_JSON="$(mktemp)"
PAYLOAD_JSON="$(mktemp)"
trap 'rm -f "$RELEASE_JSON" "$PAYLOAD_JSON" "${ALL_RELEASES_JSON:-}" "${ASSETS_JSON:-}"' EXIT
json_payload "$PAYLOAD_JSON"

# Create or update the release. Distinguish a real 404 from transient API/network
# errors so a rate-limit or outage can never accidentally create a duplicate tag.
set +e
release_code="$(curl -sSL --retry 4 --retry-delay 2 "${AUTH[@]}" \
  -o "$RELEASE_JSON" -w '%{http_code}' \
  "$API/repos/${GH_REPOSITORY}/releases/tags/${TAG_ENC}")"
curl_rc=$?
set -e
if (( curl_rc != 0 )); then
  echo "ERROR: GitHub release lookup failed for tag $RELEASE_TAG" >&2
  exit 1
fi

case "$release_code" in
  200)
    RELEASE_ID="$(python3 - "$RELEASE_JSON" <<'PY'
import json,sys
print(json.load(open(sys.argv[1],encoding='utf-8'))['id'])
PY
)"
    # Keep the existing release visibility unchanged while assets are replaced.
    # The requested final state is applied only after every canonical asset upload.
    ;;
  404)
    # GET /releases/tags/{tag} intentionally hides drafts. Reconcile a legacy
    # draft with the releases list before attempting to create a new release.
    ALL_RELEASES_JSON="$(mktemp)"
    curl -fsSL --retry 4 --retry-delay 2 "${AUTH[@]}" \
      "$API/repos/${GH_REPOSITORY}/releases?per_page=100" > "$ALL_RELEASES_JSON"
    existing_id="$(python3 - "$ALL_RELEASES_JSON" "$RELEASE_TAG" <<'PY_EXISTING'
import json,sys
for item in json.load(open(sys.argv[1], encoding='utf-8')):
    if item.get('tag_name') == sys.argv[2]:
        print(item.get('id',''))
        break
PY_EXISTING
)"
    if [[ -n "$existing_id" ]]; then
      echo "[release] reconciling existing hidden/draft release $RELEASE_TAG"
      curl -fsSL --retry 4 --retry-delay 2 "${AUTH[@]}" \
        "$API/repos/${GH_REPOSITORY}/releases/${existing_id}" > "$RELEASE_JSON"
    else
      set +e
      create_code="$(curl -sSL --retry 3 --retry-delay 2 -X POST "${AUTH[@]}" -H 'Content-Type: application/json' \
        "$API/repos/${GH_REPOSITORY}/releases" \
        --data-binary "@$PAYLOAD_JSON" \
        -o "$RELEASE_JSON" -w '%{http_code}')"
      curl_rc=$?
      set -e
      if (( curl_rc != 0 )); then
        echo "ERROR: GitHub release create request failed for tag $RELEASE_TAG" >&2
        exit 1
      fi
      if [[ "$create_code" == 422 ]]; then
        # Another actor won the create race; reconcile through the release list.
        ALL_RELEASES_JSON="$(mktemp)"
        curl -fsSL --retry 4 --retry-delay 2 "${AUTH[@]}" \
          "$API/repos/${GH_REPOSITORY}/releases?per_page=100" > "$ALL_RELEASES_JSON"
        existing_id="$(python3 - "$ALL_RELEASES_JSON" "$RELEASE_TAG" <<'PY_EXISTING2'
import json,sys
for item in json.load(open(sys.argv[1], encoding='utf-8')):
    if item.get('tag_name') == sys.argv[2]:
        print(item.get('id',''))
        break
PY_EXISTING2
)"
        [[ -n "$existing_id" ]] || { echo "ERROR: release race could not be reconciled for $RELEASE_TAG" >&2; exit 1; }
        curl -fsSL --retry 4 --retry-delay 2 "${AUTH[@]}" \
          "$API/repos/${GH_REPOSITORY}/releases/${existing_id}" > "$RELEASE_JSON"
      elif [[ ! "$create_code" =~ ^20[01]$ ]]; then
        echo "ERROR: GitHub release create failed: HTTP $create_code" >&2
        cat "$RELEASE_JSON" >&2 || true
        exit 1
      fi
    fi
    RELEASE_ID="$(python3 - "$RELEASE_JSON" <<'PY'
import json,sys
print(json.load(open(sys.argv[1],encoding='utf-8'))['id'])
PY
)"
    ;;
  *)
    echo "ERROR: GitHub release lookup returned HTTP $release_code" >&2
    cat "$RELEASE_JSON" >&2 || true
    exit 1
    ;;
esac

UPLOAD_URL="$(python3 - "$RELEASE_JSON" <<'PY'
import json,sys
print(json.load(open(sys.argv[1],encoding='utf-8')).get('upload_url','').split('{',1)[0])
PY
)"
[[ -n "$UPLOAD_URL" ]] || { echo "ERROR: release upload URL missing" >&2; exit 1; }

# Remove same-named assets before uploading refreshed artifacts.
ASSETS_JSON="$(mktemp)"
curl -fsSL --retry 4 --retry-delay 2 "${AUTH[@]}" \
  "$API/repos/${GH_REPOSITORY}/releases/${RELEASE_ID}/assets?per_page=100" > "$ASSETS_JSON"
while IFS=$'\t' read -r asset_id asset_name; do
  [[ -n "$asset_id" ]] || continue
  for file in "${ASSETS[@]}"; do
    [[ "$(basename "$file")" == "$asset_name" ]] || continue
    echo "[release] replacing existing asset $asset_name"
    curl -fsSL -X DELETE "${AUTH[@]}" "$API/repos/${GH_REPOSITORY}/releases/assets/${asset_id}" >/dev/null
  done
done < <(python3 - "$ASSETS_JSON" <<'PY'
import json,sys
for a in json.load(open(sys.argv[1], encoding='utf-8')):
    print(f"{a['id']}\t{a['name']}")
PY
)

# Do not delete handoff assets here. For a Harness-triggered build they are the
# durable transport until GitHub Actions has materialized them and relayed the
# release to Telegram. cleanup_ci_release_transients.sh removes them afterwards.
# RELEASE_CLEAN_STAGING remains accepted for compatibility with older callers.
if [[ "${RELEASE_CLEAN_STAGING,,}" == "true" ]]; then
  echo "[release] transient handoff cleanup deferred to GitHub Actions"
fi

for file in "${ASSETS[@]}"; do
  [[ -f "$file" ]] || continue
  name="$(basename "$file")"
  encoded="$(urlencode "$name")"
  echo "[release] uploading $name"
  curl -fsSL --retry 4 --retry-delay 2 -X POST "${AUTH[@]}" \
    -H 'Content-Type: application/octet-stream' \
    --data-binary "@$file" \
    "${UPLOAD_URL}?name=${encoded}" >/dev/null
done

# Finalize visibility only after all canonical assets exist. This closes the
# race where a consumer can observe a final release before its files are ready.
echo "[release] finalizing release visibility draft=$RELEASE_DRAFT prerelease=$RELEASE_PRERELEASE"
curl -fsSL --retry 4 --retry-delay 2 -X PATCH "${AUTH[@]}" \
  -H 'Content-Type: application/json' \
  "$API/repos/${GH_REPOSITORY}/releases/${RELEASE_ID}" \
  --data-binary "@$PAYLOAD_JSON" \
  > "$RELEASE_JSON"

python3 - "$RELEASE_JSON" "$RELEASE_DRAFT" "$RELEASE_PRERELEASE" <<'PY_VERIFY'
import json,sys
r=json.load(open(sys.argv[1],encoding='utf-8'))
want_draft=sys.argv[2].lower() == 'true'
want_pre=sys.argv[3].lower() == 'true'
if bool(r.get('draft')) != want_draft or bool(r.get('prerelease')) != want_pre:
    raise SystemExit(f"release visibility mismatch: got draft={r.get('draft')} prerelease={r.get('prerelease')}")
print(f"[release] visibility verified draft={r.get('draft')} prerelease={r.get('prerelease')}")
PY_VERIFY

echo "[release] published tag=$RELEASE_TAG assets=${#ASSETS[@]}"
